### ISSUE TITLE
Try running cargo clippy

### ISSUE THREAD

**Issue by sts10** [atoponce/rc4-shootout#5]
One of my favorite tools included with Cargo is Clippy (`cargo clippy`). It provides generally good advice for making your Rust code more efficient, concise, and Rust-y. I ran `cargo clippy` on this project and it spit out about 15 suggestions, some mostly stylistic but others may be good for you to consider. 

I'd make some of the changes myself and create a PR, but I don't know enough about the project to feel comfortable ensuring that the changes don't affect the goal of the code.

**Comment by atoponce** [comment]
I was actually going to look into a linter, so I'm glad you brought this up. I went ahead and followed the suggestions and pushed the changes. Thanks~
